# create your drupal and postgres config here, based off the last assignment
version: "3.1"

services:
  drupal:
    image: drupal:8.2
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:9.6
    secrets:
      - mydb_psql_password
      - mydb_psql_user
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/mydb_psql_password
      - POSTGRES_USER_FILE=/run/secrets/mydb_psql_user
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data: null
  drupal-modules: null
  drupal-profiles: null
  drupal-sites: null
  drupal-themes: null

secrets:
  mydb_psql_password:
    external: true
  mydb_psql_user:
    external: true
