name: CI - Master
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      # - name: Install pm2
      #   run: ssh staging 'sudo npm install -g pm2'

      # - name: Stop the server
      #   run: ssh staging 'pm2 delete all'

      - name: Check out the source
        run: ssh staging 'cd dungvt-bot'

      - name: Print something
        run: ssh staging 'pwd;whoami;ls -a'

      # - name: npm install
      #   run: ssh staging 'npm install'

      - name: create .env file
        run: |
          ssh staging 'cd dungvt-bot'  
          ssh staging 'touch .env'
          ssh staging 'echo token=${{ secrets.TOKEN }} >> .env'
          ssh staging 'echo clientId=${{secrets.CLIENTID}} >> .env'
          ssh staging 'echo spoonacularApi=${{secrets.SPOONACULARAPI}} >> .env'

      # - name: Start the server
      #   run: ssh staging 'pm2 start "npm run hello-cua" --name cua-bot'
